name: Stage 1 - Mini PR Security (UI)

on:
  pull_request:
    branches:
      - main
    paths:
      - 'ui/**'

jobs:
  pr-mini-security:
    name: 🔒 Mini Security Checks for UI
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      pull-requests: write

    steps:
    # ----------------- 1. Checkout -----------------
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # ----------------- 2. Node setup + tests -----------------
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install UI dependencies
      working-directory: ui
      run: npm ci

    - name: Run UI tests
      working-directory: ui
      run: npm test -- --watch=false

    # ----------------- 3. Gitleaks (secrets) -----------------
    - name: Run Gitleaks - Secret Detection
      id: gitleaks
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Gitleaks Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: gitleaks-report
        path: ${{ steps.gitleaks.outputs.report }}

    # ----------------- 4. Trivy FS Scan (source + deps) -----------------
    - name: Run Trivy Filesystem Scan (UI)
      uses: aquasecurity/trivy-action@v0.33.1
      with:
        scan-type: 'fs'
        scan-ref: 'ui'
        format: 'sarif'
        output: 'trivy-fs-results.sarif'
        severity: 'CRITICAL,HIGH'
        skip-dirs: 'node_modules'

    - name: Upload Trivy FS SARIF
      if: always()
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-fs-results.sarif'
        category: 'trivy-fs-ui'

    # ----------------- 5. Hadolint (Dockerfile lint) -----------------
    - name: Run Hadolint on UI Dockerfile
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: ui/Dockerfile
        failure-threshold: warning

    # ----------------- 6. PR Comment Summary -----------------
    - name: Comment PR with mini security summary
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          let body = '## 🔒 Mini Security Pipeline (UI)\n\n';
          body += '- ✅ Tests run (npm test)\n';
          body += '- 🔑 Gitleaks secret scan executed (see artifact **gitleaks-report**)\n';
          body += '- 🐳 Trivy filesystem scan executed (results in **Code scanning alerts**)\n';
          body += '- 📦 Dockerfile linted with Hadolint\n\n';
          body += '_This is a lightweight PR gate. More advanced scans run in the full pipeline._\n';

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body
          });
